import {
  createContext,
  use,
  useCallback,
  useEffect,
  useMemo,
  useReducer,
  useState,
  type ReactNode,
} from "react"
import type { ChatMessage, Conversation } from "@/types/chat"

const STORAGE_KEY = "manara-conversations"

interface ChatState {
  conversations: Conversation[]
  activeConversationId: string | null
}

type ChatAction =
  | { type: "HYDRATE"; state: ChatState }
  | { type: "NEW_CONVERSATION"; id: string }
  | { type: "SELECT_CONVERSATION"; id: string }
  | { type: "DELETE_CONVERSATION"; id: string }
  | { type: "ADD_MESSAGE"; conversationId: string; message: ChatMessage }
  | {
      type: "UPDATE_MESSAGE"
      conversationId: string
      messageId: string
      patch: Partial<ChatMessage>
    }

function titleFromMessage(content: string): string {
  const trimmed = content.trim()
  return trimmed.length > 48 ? `${trimmed.slice(0, 48)}…` : trimmed || "New chat"
}

function chatReducer(state: ChatState, action: ChatAction): ChatState {
  switch (action.type) {
    case "HYDRATE":
      return action.state

    case "NEW_CONVERSATION": {
      const conversation: Conversation = {
        id: action.id,
        title: "New chat",
        messages: [],
        createdAt: Date.now(),
        updatedAt: Date.now(),
      }
      return {
        conversations: [conversation, ...state.conversations],
        activeConversationId: conversation.id,
      }
    }

    case "SELECT_CONVERSATION":
      return { ...state, activeConversationId: action.id }

    case "DELETE_CONVERSATION": {
      const conversations = state.conversations.filter((c) => c.id !== action.id)
      const activeConversationId =
        state.activeConversationId === action.id
          ? (conversations[0]?.id ?? null)
          : state.activeConversationId
      return { conversations, activeConversationId }
    }

    case "ADD_MESSAGE": {
      const conversations = state.conversations.map((c) => {
        if (c.id !== action.conversationId) return c

        const isFirstUserMessage =
          action.message.role === "user" &&
          !c.messages.some((m) => m.role === "user")

        return {
          ...c,
          title: isFirstUserMessage
            ? titleFromMessage(action.message.content)
            : c.title,
          messages: [...c.messages, action.message],
          updatedAt: Date.now(),
        }
      })
      return { ...state, conversations }
    }

    case "UPDATE_MESSAGE": {
      const conversations = state.conversations.map((c) => {
        if (c.id !== action.conversationId) return c
        return {
          ...c,
          messages: c.messages.map((m) =>
            m.id === action.messageId ? { ...m, ...action.patch } : m,
          ),
          updatedAt: Date.now(),
        }
      })
      return { ...state, conversations }
    }

    default:
      return state
  }
}

const EMPTY_STATE: ChatState = { conversations: [], activeConversationId: null }

interface ChatContextValue {
  conversations: Conversation[]
  activeConversation: Conversation | null
  /** Returns the new conversation's id synchronously (generated by the
   * caller and dispatched immediately), so a message can be queued
   * against it in the same handler without waiting for a re-render. */
  newConversation: () => string
  selectConversation: (id: string) => void
  deleteConversation: (id: string) => void
  addMessage: (conversationId: string, message: ChatMessage) => void
  updateMessage: (
    conversationId: string,
    messageId: string,
    patch: Partial<ChatMessage>,
  ) => void
}

const ChatContext = createContext<ChatContextValue | null>(null)

export function ChatProvider({ children }: { children: ReactNode }) {
  const [state, dispatch] = useReducer(chatReducer, EMPTY_STATE)
  // Gates the persist effect below. Without it, the persist effect's
  // first run (which fires on every mount, including before the
  // hydrate effect's dispatch has actually been applied to `state`)
  // writes the reducer's initial EMPTY_STATE over whatever was
  // already in localStorage — silently wiping a real user's saved
  // conversation history on every page load. Found via testing real
  // persistence (not just "does hydrate read something"), which every
  // earlier phase's tests had sidestepped by clearing localStorage
  // first for test isolation, never exercising a reload with real
  // prior data. Only write once we've genuinely finished attempting
  // to read first.
  const [hydrated, setHydrated] = useState(false)

  // Hydrate from localStorage once on mount. "Frontend state only" per
  // spec — no backend persistence — but surviving a page refresh is
  // still purely a frontend concern, so it's kept here rather than lost.
  useEffect(() => {
    try {
      const raw = window.localStorage.getItem(STORAGE_KEY)
      if (raw) dispatch({ type: "HYDRATE", state: JSON.parse(raw) as ChatState })
    } catch {
      // Corrupt or inaccessible storage — start from an empty, honest state.
    } finally {
      setHydrated(true)
    }
  }, [])

  useEffect(() => {
    if (!hydrated) return
    window.localStorage.setItem(STORAGE_KEY, JSON.stringify(state))
  }, [state, hydrated])

  const newConversation = useCallback(() => {
    const id = crypto.randomUUID()
    dispatch({ type: "NEW_CONVERSATION", id })
    return id
  }, [])

  const selectConversation = useCallback(
    (id: string) => dispatch({ type: "SELECT_CONVERSATION", id }),
    [],
  )

  const deleteConversation = useCallback(
    (id: string) => dispatch({ type: "DELETE_CONVERSATION", id }),
    [],
  )

  const addMessage = useCallback(
    (conversationId: string, message: ChatMessage) =>
      dispatch({ type: "ADD_MESSAGE", conversationId, message }),
    [],
  )

  const updateMessage = useCallback(
    (conversationId: string, messageId: string, patch: Partial<ChatMessage>) =>
      dispatch({ type: "UPDATE_MESSAGE", conversationId, messageId, patch }),
    [],
  )

  const activeConversation = useMemo(
    () =>
      state.conversations.find((c) => c.id === state.activeConversationId) ?? null,
    [state.conversations, state.activeConversationId],
  )

  const value = useMemo(
    () => ({
      conversations: state.conversations,
      activeConversation,
      newConversation,
      selectConversation,
      deleteConversation,
      addMessage,
      updateMessage,
    }),
    [
      state.conversations,
      activeConversation,
      newConversation,
      selectConversation,
      deleteConversation,
      addMessage,
      updateMessage,
    ],
  )

  return <ChatContext value={value}>{children}</ChatContext>
}

export function useChat() {
  const ctx = use(ChatContext)
  if (!ctx) throw new Error("useChat must be used within ChatProvider")
  return ctx
}
